spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/spring_batch
    url: jdbc:log4jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: password
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  quartz:
    jdbc:
      initialize-schema: never
    properties:
      autoStartup: false
      org.quartz.threadPool.threadCount: 5
  batch:
    jdbc:
      initialize-schema: never
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.batch: DEBUG
